#include "engine.hlsli"
#include "slime.hlsli"
#include "math.hlsli"

cbuffer SpawnDistance : register(b3)
{
    float spawn_distance;
}

cbuffer PlayerPos : register(b4)
{
    float3 player_pos;
}

cbuffer SlimeCount : register(b5)
{
    int slime_count;
}

RWStructuredBuffer<SlimeData> slimes : register(u1);

[numthreads(64, 1, 1)]
void compute(uint3 globalID : SV_DispatchThreadID)
{
    uint index = globalID.x;

    if (slime_count > index && slimes[index].hp <= 0.0f)
    {
        float angle = rand(float2(index, time)) * PI2;

        slimes[index].position.x = player_pos.x + spawn_distance * cos(angle);
        slimes[index].position.y = player_pos.y;
        slimes[index].position.z = player_pos.z + spawn_distance * sin(angle);

        slimes[index].rotation = float3(0, 0, 0);
        slimes[index].scale = float3(1, 1, 1);

        slimes[index].velocity = float3(0, 0, 0);
        slimes[index].angular_velocity = float3(0, 0, 0);
        slimes[index].hp = 1;
    }
}