#include "engine.hlsli"
#include "slime.hlsli"
#include "math.hlsli"

cbuffer SpawnDistance : register(b3)
{
    float spawn_distance;
}

RWStructuredBuffer<SlimeData> slimes : register(u1);

[numthreads(64, 1, 1)]
void compute(uint3 globalID : SV_DispatchThreadID)
{
    uint index = globalID.x;

    float angle = rand(float2(index, time)) * PI2;
    
	slimes[index].position.x = spawn_distance * cos(angle);
    slimes[index].position.y = 5;
    slimes[index].position.z = spawn_distance * sin(angle);

    slimes[index].rotation = float3(0, 0, 0);
    slimes[index].scale = float3(1, 1, 1);
    
    slimes[index].velocity = float3(0, 0, 0);
    slimes[index].angular_velocity = float3(0, 0, 0);
    slimes[index].hp = 1;
}